import dayjs from "dayjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const { data: events } = api.events.list.useQuery();
  const today = dayjs();

  return (
    <>
      <Head>
        <title>Boone Events Cal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">Boone</span> Events Cal
          </h1>
          <div className="grid w-[768px] grid-cols-1 gap-4 sm:grid-cols-1 md:gap-8">
            {!events ? (
              <div>Loading...</div>
            ) : (
              events
                ?.filter((event) => !dayjs(event.start).isBefore(today, "day"))
                .sort((a, b) => (a.start < b.start ? -1 : 1))
                .map((event) => (
                  <Link
                    className="flex flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                    key={event.id}
                    href={event.linkUrl ?? ""}
                  >
                    <div className="flex flex-row">
                      <div>
                        <h3 className="text-2xl font-bold">
                          Event: {event.title} →
                        </h3>
                        <p>
                          Start: {dayjs(event.start).format("MMM Do, YYYY")}
                        </p>
                        <p className="mt-2">{event.description}</p>
                        <div className="mt-2">
                          <a
                            className="text-blue-300 underline"
                            href={event.linkUrl ?? ""}
                          >
                            {event.linkUrl}
                          </a>
                        </div>
                      </div>
                      {/* <div className="w-[50px]">
                        <img src={event.imageUrl ?? ""} />
                      </div> */}
                    </div>
                  </Link>
                ))
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
